spring:
  application:
    name: pm-question
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        namespace: ${NACOS_NAMESPACE:}
  config:
    import:
      - nacos:pm-common.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - nacos:pm-question.yaml?group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true
  datasource:
    password: ${coco8talk.datasource.password:}
  data:
    redis:
      password: ${coco8talk.redis.password:}

coco8talk:
  tencent:
    cos:
      secretId: ${TENCENT_COS_SECRET_ID:}
      secretKey: ${TENCENT_COS_SECRET_KEY:}
