TENCENT_COS_SECRET_ID: AKID8HRUPE6a49J5jE91u0Db8Wlqz2pZDlEl
TENCENT_COS_SECRET_KEY: WvFRWSQVaUKJ8KXenqz9BLPgqqhTAnFg
TENCENT_COS_APP_ID: 1326688809
TENCENT_COS_REGION: ap-beijing
TENCENT_COS_BUCKET_NAME: prunus-mume-1326688809